#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR="${BUILD_DIR:-build}"
QEMU="${QEMU:-qemu-system-x86_64}"
QEMU_ACCEL="${QEMU_ACCEL:-tcg}"
QEMU_MACHINE="${QEMU_MACHINE:-pc,accel=$QEMU_ACCEL}"
QEMU_EXTRA_ARGS="${QEMU_EXTRA_ARGS:-}"
IMAGE="${IMAGE:-$BUILD_DIR/disk.img}"
NC="${NC:-nc}"

SMOKE_EXPECT_PROBE_GFX="${SMOKE_EXPECT_PROBE_GFX:-1}"
SMOKE_REJECT_DOOMLOG="${SMOKE_REJECT_DOOMLOG:-}"
SMOKE_SENDKEYS="${SMOKE_SENDKEYS:-}"
SMOKE_DEFAULT_INPUT_SCRIPT="${SMOKE_DEFAULT_INPUT_SCRIPT:-launcher-select:1,wait-status=path:/APPS/DOOM/APP.ELF:90:1,snapshot generated-wad:wait-status=pmask:00000003:90:1}"
if [ -z "${SMOKE_INPUT_SCRIPT+x}" ]; then
  if [ -n "$SMOKE_SENDKEYS" ]; then
    SMOKE_INPUT_SCRIPT=""
  else
    SMOKE_INPUT_SCRIPT="$SMOKE_DEFAULT_INPUT_SCRIPT"
  fi
fi
SMOKE_REQUIRE_DOOM_PRESENT="${SMOKE_REQUIRE_DOOM_PRESENT:-0}"
SMOKE_REQUIRE_KEY_EVENT="${SMOKE_REQUIRE_KEY_EVENT:-0}"
SMOKE_REQUIRE_DOOM_GAMEPLAY="${SMOKE_REQUIRE_DOOM_GAMEPLAY:-0}"
SMOKE_REQUIRE_REAL_WAD_PROOF="${SMOKE_REQUIRE_REAL_WAD_PROOF:-0}"
SMOKE_REQUIRE_HUMAN_PLAYABILITY_PROOF="${SMOKE_REQUIRE_HUMAN_PLAYABILITY_PROOF:-0}"
SMOKE_REQUIRE_AUDIO_CONTINUITY="${SMOKE_REQUIRE_AUDIO_CONTINUITY:-0}"
SMOKE_SKIP_ASSERTIONS="${SMOKE_SKIP_ASSERTIONS:-0}"
SMOKE_NC_TIMEOUT="${SMOKE_NC_TIMEOUT:-3}"
SMOKE_QEMU_TIMEOUT="${SMOKE_QEMU_TIMEOUT:-210}"
SMOKE_EARLY_SECONDS="${SMOKE_EARLY_SECONDS:-2}"
SMOKE_SETTLE_SECONDS="${SMOKE_SETTLE_SECONDS:-5}"
SMOKE_SHUTDOWN_TIMEOUT="${SMOKE_SHUTDOWN_TIMEOUT:-5}"
SMOKE_CAPTURE_GFX="${SMOKE_CAPTURE_GFX:-1}"
SMOKE_EXPECT_GUEST_EXIT="${SMOKE_EXPECT_GUEST_EXIT:-0}"
SMOKE_GUEST_EXIT_KEYS="${SMOKE_GUEST_EXIT_KEYS:-}"
SMOKE_NO_REBOOT="${SMOKE_NO_REBOOT:-1}"
SMOKE_NO_SHUTDOWN="${SMOKE_NO_SHUTDOWN:-1}"

export BUILD_DIR QEMU QEMU_MACHINE QEMU_EXTRA_ARGS IMAGE NC
export SMOKE_NC_TIMEOUT SMOKE_QEMU_TIMEOUT SMOKE_EARLY_SECONDS
export SMOKE_SETTLE_SECONDS SMOKE_SHUTDOWN_TIMEOUT SMOKE_CAPTURE_GFX
export SMOKE_EXPECT_GUEST_EXIT SMOKE_GUEST_EXIT_KEYS SMOKE_NO_REBOOT
export SMOKE_NO_SHUTDOWN SMOKE_SENDKEYS SMOKE_INPUT_SCRIPT

tests/run_smoke_qemu.sh

export SMOKE_SKIP_ASSERTIONS SMOKE_EXPECT_PROBE_GFX SMOKE_REJECT_DOOMLOG
export SMOKE_REQUIRE_DOOM_PRESENT SMOKE_REQUIRE_KEY_EVENT
export SMOKE_REQUIRE_DOOM_GAMEPLAY SMOKE_REQUIRE_REAL_WAD_PROOF
export SMOKE_REQUIRE_HUMAN_PLAYABILITY_PROOF SMOKE_REQUIRE_AUDIO_CONTINUITY

tests/assert_smoke_status.sh
